<?php

namespace ContainerZZiqgSD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Order\OrderController' shared autowired service.
     *
     * @return \App\Controller\Order\OrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Order/OrderController.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/OrderModuleInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/OrderModule.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Handler/OrderHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ParserService/ParserService.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Order/Service/OrderParserRequest.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PriceCalculatorService/PriceCalculatorService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PaymentProcessorService/PaymentProcessorService.php';
        include_once \dirname(__DIR__, 4).'/vendor/systemeio/test-for-candidates/src/PaymentProcessor/PaypalPaymentProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/systemeio/test-for-candidates/src/PaymentProcessor/StripePaymentProcessor.php';

        $a = new \App\Service\PriceCalculatorService\PriceCalculatorService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
        $b = new \App\Service\PaymentProcessorService\PaymentProcessorService(new \Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor(), new \Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor());

        $container->services['App\\Controller\\Order\\OrderController'] = $instance = new \App\Controller\Order\OrderController(new \App\Modules\OrderModule(new \App\Modules\Handler\OrderHandler(new \App\Modules\Order\Service\OrderParserRequest(), $a, $b)), $a, $b);

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\Order\\OrderController', $container));

        return $instance;
    }
}
