<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZZiqgSD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZZiqgSD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZZiqgSD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZZiqgSD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZZiqgSD\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZZiqgSD',
    'container.build_id' => 'cb8390ea',
    'container.build_time' => 1722864316,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZZiqgSD');
